name: Update Main Repo

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  names-collect:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      REPO_NAME: ${{ steps.get-repo.outputs.repo_name }}
      GIT_SHA: ${{ steps.get-sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Get the repo name
        id: get-repo
        run: echo "repo_name=$(echo "${{ github.repository }}" | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Get the commit sha
        id: get-sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

  names-checkout:
    needs: [names-collect]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Output
        run: |
          echo ${{ needs.names-collect.outputs.REPO_NAME }}
          echo ${{ needs.names-collect.outputs.GIT_SHA }}
  
  update-deployment:
    needs: [names-collect]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Update Deployment & Save
        run: |
          git config --global credential.helper store
          git config --global user.email "pieceowater@gmail.com"
          git config --global user.name "pieceowater"
          git clone https://${{ secrets.GH_NAME }}:${{ secrets.GH_PAT }}@github.com/pieceowater/QPay.git --recursive .
  
          git submodule update --remote --recursive
  
          sed -i '' "s|${{ needs.names-collect.outputs.REPO_NAME }}:i-.*|${{ needs.names-collect.outputs.REPO_NAME }}:i-${{ needs.names-collect.outputs.GIT_SHA }}|g" docker-compose.yml
  
          git add "docker-compose.yml"
          git commit -m "Update ${{ needs.names-collect.outputs.REPO_NAME }} image to ${{ needs.names-collect.outputs.GIT_SHA }}"
          git push

