name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: eu-north-1
          registry: 058264184974.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t 058264184974.dkr.ecr.eu-north-1.amazonaws.com/qpay-backend:latest .

      - name: Push Docker image to ECR
        run: |
          docker push 058264184974.dkr.ecr.eu-north-1.amazonaws.com/qpay-backend:latest

      - name: Logout of AWS ECR
        run: aws ecr get-login-password --region eu-north-1 | docker logout https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.eu-north-1.amazonaws.com
