name: Update Parent Repo

on:
  push:
    branches:
      - main 

jobs:
  update_parent_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update parent repo
      run: |
        cd ..
        git config --global user.name "pieceowater"
        git config --global user.email "pieceowater@gmail.com"
        git add .
        git commit -m "$(echo "${{ github.repository }}" | cut -d '/' -f 2')"
        git push origin main 
